### PR TITLE
add tesseract 4 docker file

### PR DESCRIPTION
**Pull request by speedfl**

### CODE REVIEW

**Comment by speedfl** [comment]
First step done :)

This needs to create an open-ocr-2 in docker-hub then next step is to:
* Create .env file in docker-compose directory with:

```
 OPEN_OCR_VERSION=open-ocr

or 

OPEN_OCR_VERSION=open-ocr 
```

* Change in docker-compose.yml:
``` 

openocrworker:
    image: tleyden5iwx/open-ocr
    volumes:
      - ./scripts/:/opt/open-ocr/
    dns: ["8.8.8.8"]
    depends_on:
      - rabbitmq
    command: "/opt/open-ocr/open-ocr-worker -amqp_uri amqp://admin:Phaish9ohbaidei6oole@rabbitmq/"

  # Start http server
  openocr:
    image: tleyden5iwx/open-ocr
    volumes:
      - ./scripts/:/opt/open-ocr/
    ports:
      - "9292:9292"
    dns: ["8.8.8.8"]
    depends_on:
      - rabbitmq
      - openocrworker
      - strokewidthtransform
    command: "/opt/open-ocr/open-ocr-httpd -amqp_uri amqp://admin:Phaish9ohbaidei6oole@rabbitmq/ -http_port 9292"
```

with:

```
openocrworker:
    image: tleyden5iwx/${OPEN_OCR_VERSION}
    volumes:
      - ./scripts/:/opt/open-ocr/
    dns: ["8.8.8.8"]
    depends_on:
      - rabbitmq
    command: "/opt/open-ocr/open-ocr-worker -amqp_uri amqp://admin:Phaish9ohbaidei6oole@rabbitmq/"

  # Start http server
  openocr:
    image: tleyden5iwx/${OPEN_OCR_VERSION}
    volumes:
      - ./scripts/:/opt/open-ocr/
    ports:
      - "9292:9292"
    dns: ["8.8.8.8"]
    depends_on:
      - rabbitmq
      - openocrworker
      - strokewidthtransform
    command: "/opt/open-ocr/open-ocr-httpd -amqp_uri amqp://admin:Phaish9ohbaidei6oole@rabbitmq/ -http_port 9292"

```

* update the README

**Comment by tleyden** [comment]
Ok so I need to create a new build in dockerhub for open-ocr-2?

**Comment by speedfl** [comment]
Yep

**Comment by speedfl** [comment]
Keep me posted so I can test  :)
We are close to the end !!!

**Comment by tleyden** [comment]
Try this: https://hub.docker.com/r/tleyden5iwx/open-ocr-2/


```
docker pull tleyden5iwx/open-ocr-2
```

**Comment by speedfl** [comment]
Perfect thanks. Let's make a try :)

**Pull request merged**
