### PR TITLE
open-ocr-preprocessor: fix convert-pdf

### PR DESCRIPTION
**Pull request by sfcodes**
I started by fixing convert-pdf (https://github.com/tleyden/open-ocr/issues/117), but in the process ended up upgrading this entire Dockerfile.

Here is what changed:
- Upgraded to **Ubuntu:18.04,** latest LTS
- Upgraded to **Golang 1.10**
- Upgraded to **libboost 1.62**
- Upgraded to **libopencv 3.2**
- Upgraded to **tesseract 4**
- Switched from forked [tleyden/DetectText](https://github.com/tleyden/DetectText) to original [aperrault/DetectText](https://github.com/aperrault/DetectText); original seems more recently updated
- Added **Ghostscript** for convert-pdf
- Deleted stroke-width-transform Dockerfile as it seem unnecessary now given the new two-stage build process (although that's debatable)
- Converted to a [two-stage build](https://docs.docker.com/develop/develop-images/dockerfile_best-practices/#use-multi-stage-builds); which shrunk this image from 1.72GB to only **310MB**.
- [Minimized unnecessary layers](https://docs.docker.com/develop/develop-images/dockerfile_best-practices/#minimize-the-number-of-layers) by combining instructions.
- Switched to [building DetectText with cmake](https://github.com/aperrault/DetectText#using-cmake); the manual g++ method didn't seem to work for me.

All in all this should fix the build issues with the badly outdated [tleyden5iwx/open-ocr-preprocessor](https://hub.docker.com/r/tleyden5iwx/open-ocr-preprocessor) Docker image, and enable convert-pdf support.

You can pull the resulting image from here:
```
docker pull sfcodes/open-ocr-preprocessor:pr15
```

### CODE REVIEW

**Comment by tleyden** [comment]
@sfcodes so sorry, I haven't been able to get to this, but I haven't forgotten about it!

**Review by tleyden — APPROVED** [review]
LGTM.  Thanks!  I will kick off a dockerhub rebuild.

**Comment by tleyden** [comment]
Dockerhub is giving me an error:

```
Building in Docker Cloud's infrastructure...
Cloning into '.'...
Warning: Permanently added the RSA host key for IP address '140.82.114.3' to the list of known hosts.
Permission denied (publickey).
fatal: Could not read from remote repository.
Please make sure you have the correct access rights
and the repository exists.
please ensure the correct public key is added to the list of trusted keys for this repository (128)
```

Will circle back to this.

**Comment by sfcodes** [comment]
That is strange....  it works on my DockerHub just fine.  Here is the log in fact: [build_9b8800a4.txt](https://github.com/tleyden/docker/files/3616694/build_9b8800a4.txt)

Any chance you could run it again?  Maybe just a fluke.

Meanwhile I'll think about it a little more.

**Comment by tleyden** [comment]
@sfcodes I may have figured it out, and I've kicked off another build

**Comment by tleyden** [comment]
Ok it was an issue with my docker<->github account link.  It's fixed, and it build ok now.

Build logs: https://gist.github.com/tleyden/64bd251b39c1e30a8b68106feb5beffc

**Pull request merged**
