### PR TITLE
Adding caffe module to the python path

### PR DESCRIPTION
**Pull request by FreakTheMighty**
This change will make the caffe module available for import from any directory.

### CODE REVIEW

**Comment by tleyden** [comment]
Ah thanks, I needed this too

**Comment by tleyden** [comment]
Actually, I'm wondering if it isn't more appropriate to use the [ENV](https://docs.docker.com/reference/builder/#env) directive in the Dockerfile.  Thoughts?

**Comment by tleyden** [comment]
In [their docs](https://docs.docker.com/articles/dockerfile_best-practices/) they give this example:

```
ENV PATH /usr/local/postgres-$PG_MAJOR/bin:$PATH
```

Can you try that and then send another PR if it works for you?

**Comment by tleyden** [comment]
I reverted the changes for now.

**Comment by FreakTheMighty** [comment]
I'm running a new build now. I'll update when I've confirmed it works.

**Comment by tleyden** [comment]
@FreakTheMighty any update?

**Comment by FreakTheMighty** [comment]
I'm having issues rebuilding the image. I'm using boot2docker and it appears that the VM is running out of space. I'll need to set aside some time to figure this out.

**Comment by tleyden** [comment]
@FreakTheMighty ok np, I just updated it in https://github.com/tleyden/docker/commit/463ed5deefc5bd74864a2e8444591d4471c7962f and kicked off a [build](https://registry.hub.docker.com/u/tleyden5iwx/caffe-cpu-master/build_id/29169/code/b3udqnk2yqld5dwcy5jgrpt/)

Hopefully this will work (I'm wondering if $PYTHONPATH will actually get resolved, or if it will be added in literally)

**Comment by tleyden** [comment]
That didn't fully work:

```
root@80e673baa6f5:/# echo $PYTHONPATH
/opt/caffe/python:$PYTHONPATH
```

**Comment by tleyden** [comment]
I ended up doing this:

```
ENV PYTHONPATH /opt/caffe/python
```

if more things are needed for that ENV variable, we can use the approach documented here:  https://github.com/docker/docker/pull/1175#issuecomment-31285150

**Pull request merged**
