### PR TITLE
Dependency to use the tool draw_net.py

### PR DESCRIPTION
**Pull request by boechat107**
`draw_net.py` is a tool to draw an image representation of a NN architecture.

This small change may be useful for the other Caffe's Dockerfiles.

### CODE REVIEW

**Comment by tleyden** [comment]
Thanks!  Are you using any of the docker images on dockerhub that I need to make sure get rebuilt?

**Comment by boechat107** [comment]
For now, I'm using only this Dockerfile. Probably I'll use the gpu mode (master) soon.

Thanks!

**Comment by tleyden** [comment]
Hmm, looks like this caused a build failure:

https://registry.hub.docker.com/u/tleyden5iwx/caffe-cpu-master/build_id/29169/code/bvncejjhbqsj585ops5suqs/

**Comment by boechat107** [comment]
Yes, I can see that an error was raised, but I can see the details (permission problem). It's weird because I just installed that package when I was using this docker image.

**Pull request merged**
